Adding error message back and testing with non-existent app

diff --git a/.github/workflows/promote-images.yml b/.github/workflows/promote-images.yml
--- a/.github/workflows/promote-images.yml
+++ b/.github/workflows/promote-images.yml
@@ -10,6 +10,7 @@ on:
           - all
           - app1
           - app2
+          - app3
       promote:
         type: choice
         options:
@@ -59,6 +60,10 @@ jobs:
           # https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28#list-package-versions-for-a-package-owned-by-an-organization
           # Using "%2f" instead of "/" because we have to use this in a REST API.
           current_tag=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/${github_repo}%2f${{ matrix.image }}/versions" | jq -r '.[].metadata.container.tags[]' | grep -E "^${from_env}-[0-9a-f]{7}-[0-9]+$" | sort -R | sort --field-separator=- -k 3 -r | head -n 1)
+          if [[ -z "${current_tag}" ]]; then
+            echo "ERROR: Could not find container with tag matching regex /${from_env}-[0-9a-f]{7}-[0-9]+/"
+            exit 1
+          fi
           docker pull \
             "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${current_tag}"
           new_tag=$(echo ${current_tag} | sed -E "s/.*-([^-]+)-([^-]+)/${to_env}-\1-\2/")
